openapi: 3.2.0
info:
  title: Nory Middleware - Sandbox Environment Integration API
  version: 1.0.0
  description: Nory
servers:
- https://sandbox.nory.ai
- http://localhost:8000
tags:
- name: Integration
paths:
  /integration/{id}/{integrationName}/{type}:
    get:
      tags:
      - Integration
      name: Get Integration Data
      summary: Get Data from Integration service
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      - in: path
        name: integrationName
        schema:
          type: string
        required: true
      - in: path
        name: type
        schema:
          type: string
        required: true
      - in: query
        name: from
        schema:
          type: string
        required:
        - name
      - in: query
        name: to
        schema:
          type: string
        required:
        - name
      responses:
        '200':
          description: Requested data
        '401':
          description: Permission error
        '500':
          description: Internal server error
      operationId: getIntegrationByIdByIntegrationNameByType
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Authorization
      scheme: bearer
      in: header
