openapi: 3.2.0
info:
  title: Nory Middleware - Sandbox Environment Inventory API
  version: 1.0.0
  description: Nory
servers:
- https://sandbox.nory.ai
- http://localhost:8000
tags:
- name: Inventory
paths:
  /inventory/ingest:
    post:
      tags:
      - Inventory
      name: Ingest
      summary: Ingest items / batch items / menu items
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful ingest message
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: string
        '400':
          description: Incorrect data supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
        '401':
          description: No auth token
        '403':
          description: JWT token and username from client don't match
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ingest'
      operationId: postInventoryIngest
      x-operation-id-source: derived
  /inventory/branches/{branchId}/counts:
    get:
      tags:
      - Inventory
      name: Counts
      summary: Get counts of a branch
      security:
      - bearerAuth: []
      parameters:
      - in: path
        name: branchId
        schema: string
        required: true
      responses:
        '200':
          description: List of counts
          content:
            application/json:
              schema:
                type: object
                properties:
                  counts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Count'
        '400':
          description: Incorrect data supplied
        '401':
          description: No auth token
        '403':
          description: JWT token and username from client don't match
      operationId: getInventoryBranchesByBranchIdCounts
      x-operation-id-source: derived
    post:
      tags:
      - Inventory
      name: Counts
      summary: Create a count
      security:
      - bearerAuth: []
      parameters:
      - in: path
        name: branchId
        schema: string
        required: true
      responses:
        '200':
          description: Created count
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    $ref: '#/components/schemas/Count'
        '400':
          description: Incorrect data supplied
        '401':
          description: No auth token
        '403':
          description: JWT token and username from client don't match
        '500':
          description: Unexpected error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Count'
      operationId: postInventoryBranchesByBranchIdCounts
      x-operation-id-source: derived
  /inventory/branches/{branchId}/deliveries:
    get:
      tags:
      - Inventory
      name: Deliveries
      summary: Get deliveries of a branch
      security:
      - bearerAuth: []
      parameters:
      - in: path
        name: branchId
        schema: string
        required: true
      responses:
        '200':
          description: List of deliveries
          content:
            application/json:
              schema:
                type: object
                properties:
                  deliveries:
                    type: array
                    items:
                      $ref: '#/components/schemas/Delivery'
        '400':
          description: Incorrect data supplied
        '401':
          description: No auth token
        '403':
          description: JWT token and username from client don't match
      operationId: getInventoryBranchesByBranchIdDeliveries
      x-operation-id-source: derived
  /inventory/suppliers:
    get:
      tags:
      - Inventory
      name: Suppliers
      summary: Get all suppliers
      security:
      - bearerAuth: []
      responses:
        '200':
          description: List of suppliers
          content:
            application/json:
              schema:
                type: object
                properties:
                  suppliers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Supplier'
        '400':
          description: Incorrect data supplied
        '401':
          description: No auth token
        '403':
          description: JWT token and username from client don't match
      operationId: getInventorySuppliers
      x-operation-id-source: derived
components:
  schemas:
    BaseUnit:
      type: object
      properties:
        unit_of_measure:
          type: number
    Count:
      type: object
      properties:
        id:
          type: string
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
        type:
          type: string
          enum:
          - full
        status:
          type: string
          enum:
          - draft
          - completed
        branch_id:
          type: string
        brand_item_counts:
          type: array
          items:
            $ref: '#/components/schemas/BrandItemCount'
    Ingest:
      type: object
      properties:
        brand_id:
          type: string
        ingest_type:
          type: string
        content:
          type: string
    Unit:
      type: object
      properties:
        unit_type:
          type: string
          enum:
          - base
          - package
          - case
        unit_body:
          $ref: '#/components/schemas/BaseUnit'
    BrandItemUnitCount:
      type: object
      properties:
        unit:
          type: array
          items:
            $ref: '#/components/schemas/Unit'
        quantity:
          type: number
    BrandItemCount:
      type: object
      properties:
        brand_item:
          type: string
        unit_counts:
          type: array
          items:
            $ref: '#/components/schemas/BrandItemUnitCount'
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Authorization
      scheme: bearer
      in: header
