swagger: '2.0'
info:
  title: Nory Middleware - Sandbox Environment Authorization API
  version: 1.0.0
  description: 'Nory '
servers:
- https://sandbox.nory.ai
- http://localhost:8000
basePath: /app/v1/
schemes:
- https
- http
tags:
- name: Authorization
paths:
  /auth/token:
    post:
      tags:
      - Authorization
      name: Token
      summary: Get Access and Refresh tokens
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
              format: password
        required:
        - email
        - password
      responses:
        '200':
          description: Token Sucess
        '401':
          description: Bad username, not found in db
        '403':
          description: Username and password don't match
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    scheme: bearer
    in: header
