swagger: '2.0'
info:
  title: Nory Middleware - Sandbox Environment Authorization Location Settings API
  version: 1.0.0
  description: 'Nory '
servers:
- https://sandbox.nory.ai
- http://localhost:8000
basePath: /app/v1/
schemes:
- https
- http
tags:
- name: Location Settings
paths:
  /settings/customHolidays/{id}:
    get:
      tags:
      - Location Settings
      name: Get custom holidays by ID
      summary: Get custom holidays for a location
      security:
      - bearerAuth: []
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required:
        - name
      responses:
        '200':
          description: Requested data
          schema: null
        '401':
          description: Permission error
        '500':
          description: Internal server error
    post:
      tags:
      - Location Settings
      name: Create custom holidays for a location by ID
      summary: Create custom holidays for a location by ID
      security:
      - bearerAuth: []
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        schema:
          type: string
      - in: body
        name: body
      responses:
        '204':
          description: Requested data
          schema: null
        '400':
          description: Bad request
        '401':
          description: Permission error
        '500':
          description: Internal server error
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    scheme: bearer
    in: header
