openapi: 3.2.0
info:
  title: Nory Middleware - Sandbox Environment Refresh token API
  version: 1.0.0
  description: Nory
servers:
- https://sandbox.nory.ai
- http://localhost:8000
tags:
- name: Refresh Token
paths:
  /auth/refreshToken:
    post:
      tags:
      - Refresh Token
      name: Refresh Token
      summary: Get new Access Token by passing Refresh Token, pass the RefershToken along with…
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Token Sucess
        '401':
          description: Bad username, not found in db
        '403':
          description: Username and password don't match
      operationId: postAuthRefreshToken
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Authorization
      scheme: bearer
      in: header
