openapi: 3.2.0
info:
  title: Nory Middleware - Sandbox Environment Authorization API
  version: 1.0.0
  description: Nory
servers:
- https://sandbox.nory.ai
- http://localhost:8000
tags:
- name: Authorization
paths:
  /auth/token:
    post:
      tags:
      - Authorization
      name: Token
      summary: Get Access and Refresh tokens
      responses:
        '200':
          description: Token Sucess
        '401':
          description: Bad username, not found in db
        '403':
          description: Username and password don't match
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  format: password
        required: true
      operationId: postAuthToken
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Authorization
      scheme: bearer
      in: header
